{
 "title": "Test Dashboard 2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "timeInterval",
    "query": "1s,5s,10s,30s,1m,3m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Get Data Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Success requests ratio (% of success checks)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "success",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "checks",
       "query": "SELECT last(success) from \n(\nSELECT count(value) as success FROM checks where ( value=1 and check= 'getRequest has status 200' and time >= ${__from}ms )\n)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "check", "operator": "=", "value": "" }
       ]
      },
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "checks",
       "query": "SELECT last(allRequests) from \n(\nSELECT count(value) as allRequests FROM checks where ( check= 'getRequest has status 200' and time >= ${__from}ms )\n)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total request time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "alias": "mean",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time($timeInterval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT min(\"value\") FROM \"http_req_duration\" WHERE (\"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time($timeInterval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT max(\"value\") FROM \"http_req_duration\" WHERE (\"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time($timeInterval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Endpoint statistics",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "alias": "Number of users",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "checks",
       "query": "select count(\"value\") from vus GROUP BY time($timeInterval) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "check", "operator": "=", "value": "" }
       ]
      },
      {
       "alias": "Number of requests",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_reqs",
       "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time($timeInterval) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "" }
       ]
      },
      {
       "alias": "200 status requests",
       "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"status\" = '200' AND \"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(null) ORDER BY time DESC"
      },
      {
       "alias": "401 errors",
       "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"status\" = '401' AND \"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
      },
      {
       "alias": "Other 4xx errors",
       "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"status\" =~ /^(400|403|404)$/ AND \"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
      },
      {
       "alias": "5xx errors",
       "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"status\" =~ /^(500|501|502|503|504)$/ AND \"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
      },
      {
       "alias": "Min request time [ms]",
       "query": "SELECT min(\"value\")  FROM \"http_req_duration\" WHERE (\"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
      },
      {
       "alias": "Max request time [ms]",
       "query": "SELECT max(\"value\")  FROM \"http_req_duration\" WHERE (\"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
      },
      {
       "alias": "Avg request time[ms]",
       "query": "SELECT mean(\"value\")  FROM \"http_req_duration\" WHERE (\"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
      },
      {
       "alias": "Median request time[ms]",
       "query": "SELECT median(\"value\")  FROM \"http_req_duration\" WHERE (\"group\" = '::get data from endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Post Data Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success requests ratio (% of success checks)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "checks",
     "query": "SELECT last(success) from \n(\nSELECT count(value) as success FROM checks where ( value=1 and check= 'postRequest has status 200' and time >= ${__from}ms )\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "check", "operator": "=", "value": "" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "checks",
     "query": "SELECT last(allRequests) from \n(\nSELECT count(value) as allRequests FROM checks where ( check= 'postRequest has status 200' and time >= ${__from}ms )\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time($timeInterval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT min(\"value\") FROM \"http_req_duration\" WHERE (\"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time($timeInterval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT max(\"value\") FROM \"http_req_duration\" WHERE (\"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time($timeInterval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "&" }
     ]
    }
   ]
  },
  {
   "title": "Endpoint statistics",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Number of users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "checks",
     "query": "select count(\"value\") from vus GROUP BY time($timeInterval) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "check", "operator": "=", "value": "" }
     ]
    },
    {
     "alias": "Number of requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time($timeInterval) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "" }
     ]
    },
    {
     "alias": "200 status requests",
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"status\" = '200' AND \"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(null) ORDER BY time DESC"
    },
    {
     "alias": "401 errors",
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"status\" =~ /^(401)$/ AND \"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
    },
    {
     "alias": "Other 4xx errors",
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"status\" =~ /^(400|403|404)$/ AND \"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
    },
    {
     "alias": "5xx errors",
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"status\" =~ /^(500|501|502|503|504)$/ AND \"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
    },
    {
     "alias": "Min request time [ms]",
     "query": "SELECT min(\"value\")  FROM \"http_req_duration\" WHERE (\"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
    },
    {
     "alias": "Max request time [ms]",
     "query": "SELECT max(\"value\")  FROM \"http_req_duration\" WHERE (\"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
    },
    {
     "alias": "Avg request time[ms]",
     "query": "SELECT mean(\"value\")  FROM \"http_req_duration\" WHERE (\"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
    },
    {
     "alias": "Median request time[ms]",
     "query": "SELECT median(\"value\")  FROM \"http_req_duration\" WHERE (\"group\" = '::post data to endpoint') AND $timeFilter GROUP BY time(${timeInterval}) fill(0) ORDER BY time DESC"
    }
   ]
  }
 ]
}